### ISSUE TITLE
could you explain how to train this network with a custom dataset?

### ISSUE THREAD

**Issue by GiovanniPasq** [kevinhkhsu/DA_detection#8]
could you explain which parts i need to change in order to use my dataset?

**Comment by kevinhkhsu** [comment]
The main code you would need to modify is under the ./lib/datasets folder. In that folder, you can copy one of the {KITTI, bdd100k, cityscapes} code and change according to your needs. Afterward, you would need to add that dataset into ./lib/datasets/factory.py and give it a name. Then you should be able to specify your dataset in one of the scripts in ./experiments/scripts. These are the major changes to get your dataset up and running.

**Comment by life97** [comment]
> The main code you would need to modify is under the ./lib/datasets folder. In that folder, you can copy one of the {KITTI, bdd100k, cityscapes} code and change according to your needs. Afterward, you would need to add that dataset into ./lib/datasets/factory.py and give it a name. Then you should be able to specify your dataset in one of the scripts in ./experiments/scripts. These are the major changes to get your dataset up and running.

Which pre-trained weights will be used to customize the data set in the first phase of the training network? If you can reply, thank you very much.

**Comment by darkhan-s** [comment]
> Which pre-trained weights will be used to customize the data set in the first phase of the training network? If you can reply, thank you very much.

Hi @life97, have you figured this out?

**Comment by life97** [comment]
> 

According to the author's process, the model can be run through. I used this model to train the network on a custom domain-adapted scene dataset. The network training is divided into two stages, the first stage is the source domain to the intermediate domain, and the second stage is the intermediate domain to the target domain. The CycleGAN is jointly trained by the source domain and the target domain to synthesize the intermediate domain images, and the weights of the intermediate domain images are the discriminator outputs of the trained CycleGAN. It's been a long time, I probably remember it like this, I hope it helps you.

**Comment by darkhan-s** [comment]
@life97 thank you for your reply. I have generated my custom dataset from PyTorch CycleGAN, but still couldnt understand which pre-trained weights to use with it. Would it be the weights from CycleGAN?

**Comment by life97** [comment]
修改H:\19xyy\project\DA_detection-master\PyTorch-CycleGAN\models.py中判别器的返回值：
![QQ截图20220405192301](https://user-images.githubusercontent.com/56705432/161743569-00c9fd07-0cf7-45d1-9ee1-26959370b31f.jpg)
由行92改成行93
![QQ截图20220405192618](https://user-images.githubusercontent.com/56705432/161743971-45051754-c645-4699-95f3-f2cd979ff5d1.jpg)
主要是修改PyTorch-CycleGAN中：datasets.py和test.py
我是这样改的，大体思路是这样的，我也不确定这样对不对，你可以试试~
有错误的话，欢迎指正，希望有帮助到你~

**Comment by life97** [comment]
> @life97 thank you for your reply. I have generated my custom dataset from PyTorch CycleGAN, but still couldnt understand which pre-trained weights to use with it. Would it be the weights from CycleGAN?

Step 1: Modify the return value of the discriminator in H:\19xyy\project\DA_detection-master\PyTorch-CycleGAN\models.py: (change from line 92 to line 93)

![QQ截图20220405192301](https://user-images.githubusercontent.com/56705432/161749143-78f9911e-2f2e-404f-b932-74140ab06f9a.jpg)
Step 2: Modify test.py as needed
![QQ截图20220405192618](https://user-images.githubusercontent.com/56705432/161749180-9a642791-35ce-4dc3-b932-bfe6993c0266.jpg)

Mainly modify PyTorch-CycleGAN: datasets.py and test.py
I changed it like this, the general idea is this, I'm not sure if this is right, you can try~
If there are any mistakes, please correct me, I hope it helps you~
